# Generated by Django 3.2.5 on 2021-08-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20210804_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_opened',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
