# Generated by Django 3.2.5 on 2021-08-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20210804_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
    ]
